### ISSUE TITLE
Im a big idiot meaning this might be understood, but

### ISSUE THREAD

**Issue by miqumi** [devendrn/renderdragon-shaders#5]
https://devendrn.github.io/renderdragon-shaders/docs/build.html#setup-workspace
Shouldn't there be `cd RenderDragonSourceCodeInv` between 1 and 2?

**Comment by devendrn** [comment]
Yeah. But I assumed most users would understand that they are supposed to go inside the folder first, either by using `cd` or by opening command prompt inside that folder.

If you think your change would improve it, you can make a PR with that addition. I will consider merging it.

**Comment by miqumi** [comment]
> Yeah. But I assumed most users would understand that they are supposed to go inside the folder first  
Makes sense, though it's kind of a convention.

![image](https://github.com/devendrn/renderdragon-shaders/assets/80510430/71f4bf68-47ba-4034-8744-b95a40d7756a)
Is this satisfactory enough or should it be in step 1?

**Comment by devendrn** [comment]
Yeah that's good enough. It would also be better if you make this addition as well. 
`2. Go inside directory and run setup. This will...`

**Comment by miqumi** [comment]
> Yeah that's good enough. It would also be better if you make this addition as well. `2. Go inside directory and run setup. This will...`

Okie sure
